// Les nouveautés de la version en cours — affichées UNE fois dans le pop-up
// « Quoi de neuf », signé ILY. Mises à jour à chaque déploiement.
export const NOTES_VERSION: string[] = [
  '🚦 Les bouchons apparaissent ENFIN sur la carte : les portions ralenties viennent maintenant du calcul de la route lui-même, elles se superposent donc exactement au tracé bleu (orange = ça freine, rouge = ça bouchonne, noir = route coupée). Touche une portion : le retard en minutes et la vitesse réelle.',
  '🔎 Les incidents nommés (accident, travaux) étaient filtrés bien trop sévèrement : l’app comparait leur position à seulement 24 repères espacés de 30 km, et les jetait presque tous. Elle compare désormais au tracé détaillé.',
  '\ud83d\udea6 BOUCHONS EN DIRECT SUR LA CARTE, comme sur Waze : accidents, ralentissements, travaux et routes coupées sont peints sur le trajet (jaune → orange → rouge → noir), avec le retard de chacun. Un interrupteur « Bouchons » pour les masquer, et les trois pires listés en clair.',
  '\ud83e\uddea NOUVEAU : un banc d’essai automatique ouvre les 58 écrans de l’app dans un vrai navigateur et appuie sur leurs boutons avant chaque mise à jour — d’abord avec des données normales, puis avec des données volontairement abîmées et des serveurs en panne. Plus rien ne part sans être passé par là.',
  '\ud83d\udee1\ufe0f 16 plantages trouvés et corrigés par ce banc d’essai — dont un gros : si les réglages du foyer étaient vides, QUINZE écrans tombaient d’un coup (Voyages, Plages, Pharmacies, Carburant, Cours d’eau, Radar…). Réparé à la source.',
  '\ud83d\udc8a Fiche médicament : le message d’erreur disait « photo floue » alors que c’était l’IA qui était saturée. L’app affiche désormais la VRAIE raison, avec un bouton « Réessayer ».',
  '🧭 Étapes réparées à la racine : les coordonnées sont maintenant envoyées TELLES QUELLES à TomTom (qui sait déjà les accrocher à la route). Le « recalage » automatique que j’avais ajouté pouvait déplacer une étape parfaitement correcte — il ne sert plus qu’en secours, et refuse tout déplacement de plus de 5 km.',
  '🧭 Étape introuvable sur la route : l’app repère MAINTENANT laquelle bloque, calcule le trajet sans elle, et te le dit en clair (« Corrige l’étape dans Étapes et coûts ») au lieu d’afficher une erreur.',
  '🔎 Les étapes sont géocodées en privilégiant la France, et leur nom affiche la région (ou le pays s’il est étranger) : on voit tout de suite si c’est la bonne commune et non une homonyme à l’autre bout du monde.',
  '🧭 Étapes : le calcul ne peut plus échouer en « erreur 400 ». L’app essaie plusieurs façons de demander la route à TomTom, et si aucune ne passe, elle calcule chaque segment séparément (maison → étape, étape → destination) et les recolle — durée, kilomètres et péage additionnés.',
  '📍 Les arrêts sur la route changent de source : c’est désormais TomTom (le même service que le calcul du trajet) qui les cherche LE LONG de l’itinéraire — rapide et fiable. OpenStreetMap ne vient plus qu’en complément, et ne peut plus bloquer l’affichage.',
  '🔎 Les filtres (aires, essence, gonflage, eau, curiosités) et le nombre d’arrêts trouvés sont maintenant AU-DESSUS de la carte : plus besoin de faire défiler pour savoir où en est la recherche.',
  '↩️ Le menu (et tous les écrans) retrouvent leur place : quand tu reviens en arrière, tu repars exactement d’où tu t’étais arrêté — fini le déroulement à chaque fois.',
  '📍 Arrêts sur la carte : la recherche passe par une douzaine de petites requêtes le long du trajet (bien plus fiables), et si rien ne remonte, l’app affiche enfin la raison.',
  '📍 Les arrêts s’affichent enfin SUR la carte : aires de repos, stations, gonflage, points de vue et eau potable — la recherche était lancée en une seule fois sur tout le trajet et expirait ; elle est maintenant découpée en tronçons interrogés en parallèle.',
  '🧭 Étapes réparées : un arrêt géocodé en pleine campagne faisait échouer tout le calcul — chaque étape est maintenant « accrochée » à la route la plus proche.',
  '🛣 Péage enfin calculé : les kilomètres d’autoroute payante sont mesurés sur le tracé réel (TomTom les donne en repères, pas en distances).',
  '💶 Budget complet du trajet : aller ET aller-retour, litres de carburant nécessaires, coût du péage, durée avec bouchons, pauses conseillées et heure d’arrivée estimée.',
  '🚗 Choisis la VOITURE du voyage : le Hyundai Tucson hybride de Stéphane (6,3 L) ou l’Opel Astra 2023 de Tiphaine (5,8 L) — le coût du trajet s’adapte tout seul. Consommations et prix modifiables, et tu peux ajouter d’autres véhicules.',
  '🛠 Corrigé : ajouter une étape faisait échouer le calcul de la route (« tomtom 400 »).',
  '🗺 Voyages : l’app compare jusqu’à 3 itinéraires et propose LE PLUS RAPIDE du moment. Touche « Voir la carte » → la route dessinée, avec les aires de repos, stations-service, gonflage pneus, points de vue et eau potable sur le trajet (filtrables, « Y aller » en un appui).',
  '💶 Le coût du trajet est estimé : carburant (selon la conso de ta voiture) + péage — réglable dans « 🧭 Étapes et coûts ».',
  '🧭 Étapes multiples : ajoute autant d’arrêts que tu veux entre la maison et la destination, réordonne-les — la route, les bouchons et le coût se recalculent.',
  '✈️ Les voyages se modifient et se suppriment : ✏️ dans la liste (ou depuis la fiche du voyage) — titre, destination, dates. La suppression demande confirmation et prévient de ce qui part avec (les photos souvenirs, elles, restent).',
  '🚦 Trafic réparé : TomTom ne renvoyait pas le temps « sans bouchons » — l’app le demande désormais explicitement et sait le déduire.',
  '🛡️ GRANDE RÉVISION : toute l’application a été passée au peigne fin, écran par écran, bouton par bouton. Une centaine de bugs corrigés — sans toucher à la moindre de vos données.',
  '🚫 Une page qui plante ne bloque PLUS l’app : elle seule est concernée, la barre du bas reste utilisable et un bouton ramène au tableau de bord sans recharger.',
  '💾 Vos saisies ne peuvent plus se perdre : une coupure réseau est désormais reconnue comme telle et la modification est réessayée au lieu d’être abandonnée.',
  '📅 Calendriers Apple : une synchro qui échouait pouvait effacer des événements — c’est réparé, plus rien n’est supprimé si la lecture ne réussit pas.',
  '⚡ Tableau de bord plus rapide et plus juste : fini le rechargement en boucle, les événements « toute la journée » réapparaissent, et plus aucune date bizarre.',
  '🗓 Agenda : une heure effacée ne fait plus écran blanc, et « tous les mois » depuis un 31 tombe enfin au bon jour.',
  '🛣 Chaque voyage affiche l’ÉTAT DE LA ROUTE depuis la maison : durée réelle, kilomètres et bouchons en direct.',
  '🏖 Les Plages (eaux de baignade + webcams) et 🏠 Autour de chez nous (ventes immobilières réelles du quartier).',
  '💊 Photographie une boîte de médicament → fiche claire · 🖼 photo d’astronomie du jour · 🕰 le temps qu’il faisait il y a un an.',
]
